@hostname = http://127.0.0.1

@port = 8080

### Create new account

POST {{hostname}}:{{port}}/accounts
Content-Type: "application/json"

{
    "owner": "Anna",
    "currency": "USD"
}

### Get account by id

GET {{hostname}}:{{port}}/accounts/1 HTTP/1.1
Accept: application/json

### Get accounts list
GET {{hostname}}:{{port}}/accounts/?page_id=5&page_size=5
Accept: application/json

### Delete account by id
DELETE {{hostname}}:{{port}}/accounts/11
Accept: application/json

### Create new account via curl

curl -X POST http://127.0.0.1:8080/accounts \
    -H "Content-Type: application/json" \
    -d '{"owner":"John","currency":"EUR"}'

