@hostname = http://127.0.0.1

@port = 8080

### Create new account

POST {{hostname}}:{{port}}/accounts
Content-Type: "application/json"

{
    "owner": "Vasya",
    "currency": "USD"
}

### Create new account via curl

curl -X POST http://127.0.0.1:8080/accounts \
    -H "Content-Type: application/json" \
    -d '{"owner":"John","currency":"EUR"}'